### ISSUE TITLE
Cannot build MinGfx on Windows 64

### ISSUE THREAD

**Issue by Danielwbolson** [ivlab/MinGfx#15]
Limitation seems to be that NanoGUI is default built as a 32bit system, most likely due to the new way that CMake has changed up it's gui structure. Default is now Win32

**Comment by dtorban** [comment]
We will need to add the following to the NanoGUI auto build:
`-DCMAKE_GENERATOR_PLATFORM=${CMAKE_GENERATOR_PLATFORM}`
