### ISSUE TITLE
Cannot build documentation

### ISSUE THREAD

**Issue by jharwell** [ivlab/MinGfx#4]
When I do `-DWITH_DOCUMENTATION=yes`, it cannot find the Doxyfile.in, which appears to be missing from version control?

**Comment by dtorban** [comment]
Yes, I noticed this as well.  Perhaps Dan forgot to check it in.  I created one myself when I built the documentation, but I imagine Dan already has one.

**Comment by dankeefe** [comment]
Actually, I don't already have one.  It would be great if you could check
yours in.
D


---
Daniel Keefe, Ph.D.
Associate Professor
Department of Computer Science & Engineering
University of Minnesota
www.cs.umn.edu/~keefe
