### ISSUE TITLE
Nanogui not installed along with MinGfx

### ISSUE THREAD

**Issue by jharwell** [ivlab/MinGfx#5]
Could this be added? Our project does not use cmake (too difficult for 3081 students), so we cannot use `CMAKE_PREFIX_PATH` to get the nanogui include/linking definitions that MinGfx uses.

**Comment by dtorban** [comment]
I don't completely understand the question.  It is possible to auto build NanoGUI along side MinGfx as follows:

```bash
cmake .. -DAUTOBUILD_NANOGUI=ON
```

However, that might not be the question.  Is the problem that we cannot use cmake to build MinGfx?

**Comment by jharwell** [comment]
No the problem was I was installing MinGfx to the wrong location :1st_place_medal: , which was causing missing headers when compiling our project.

**Comment by dankeefe** [comment]
So John, is this working for you now?  I think MinGfx does install nanogui
and all its depends.
D


---
Daniel Keefe, Ph.D.
Associate Professor
Department of Computer Science & Engineering
University of Minnesota
www.cs.umn.edu/~keefe

**Comment by jharwell** [comment]
Yes indeed it is--this one was my mistake .
